#!/usr/bin/env python3

import rospy
import time

from roschat_msgs.msg import *
from std_msgs.msg import String

def say_callback(data, node):
    node.say_callback(data)

class RosChatServerNode:
    def __init__(self):
        rospy.init_node("roschat_server_node")
        self.channel = rospy.get_param("~channel", "chat")

    def run(self):
        self.chat_sub = rospy.Subscriber(self.channel, RosChat, say_callback, callback_args=self)
        self.chat_repub = rospy.Publisher("{0}/lurk".format(self.channel), String, queue_size=10)

        rospy.spin()

    def say_callback(self, data):
        msg = String()
        msg.data = "{0} {1}: {2}".format(time.strftime("%Y-%m-%d %H:%M:%S"), data.sender, data.message)
        self.chat_repub.publish(msg)

if __name__=="__main__":
    node = RosChatServerNode()
    node.run()
